name: Go
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [ opened, reopened, synchronize ]
    paths: [go]

permissions:
  contents: read # for checkout

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5.0.0
      - name: Install dependencies
        run: cd go && go mod download
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          docker-compose up -d
          popd
      - name: Run tests
        run: cd go && make run-tests
  lint:
    name: Check code format for Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v4.0.0
      - name: Run gofmt
        run: cd go && make check-format