name: JS
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [ opened, reopened, synchronize ]
    paths: [ "js/**" ]

permissions:
  contents: read # for checkout

jobs:
  lint:
    name: Check code format for JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: cd js && yarn install
      - name: Prepare environment
        run: cd js && yarn lint:check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: cd js && yarn install
      - name: Run local-setup
        run: |
          git clone https://github.com/matter-labs/local-setup.git
          pushd local-setup
          docker-compose up -d
          popd
      - name: Wait for local-setup to be ready
        run: cd js && yarn test:wait
      - name: Prepare environment
        run: cd js && yarn test:prepare
      - name: Run tests
        run: cd js && yarn test